eWallet/eWallet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wallet.urls')),
    path('', include('portfolio.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

eWallet/portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('user_home/', views.user_home, name="user_home"),
    path('posts/', views.posts, name="posts"),
    path('post/<slug:slug>/', views.post, name="post"),



    #CRUD paths
    path('create_post/', views.createPost, name="create_post"),
    path('update_post/<slug:slug>/', views.updatePost, name="update_post"),
    path('delete_post/<slug:slug>/', views.deletePost, name="delete_post"),

    path('send_email/', views.sendEmail, name="send_email"),

]

eWallet/wallet/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('dashboard/', views.dashboard, name="dashboard"),

    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),





]

eWallet/portfolio/models.py
#models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
import wallet.models

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Post(models.Model):
    #customer = models.ForeignKey("wallet.Customer",null=True, on_delete=models.SET_NULL)
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to='images', default='placeholder.png')
    body = RichTextUploadingField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, null=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.headline

    def save(self, *args, **kwargs):
        if self.slug == None:
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()

            self.slug = slug

        super().save(*args, **kwargs)

eWallet/portfolio/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('__all__')

        widgets = {
            'tags':forms.CheckboxSelectMultiple(),

        }
    

eWallet/portfolio/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import PostForm

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

from .filters import PostFilter
from django.core.paginator import Paginator , EmptyPage, PageNotAnInteger

from wallet.decorators import unauthenticated_user, allowed_users, admin_only
import  wallet.models
from wallet.forms import CustomerForm as CF

# Create your views here.

@login_required(login_url="login")
@allowed_users(allowed_roles=['customer','admin'])
def user_home(request):
    customer = request.user.customer
    form = CF(instance=customer)

    if request.method == 'POST':
        form = CF(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()

    #posts = Post.objects.filter(active=True, featured=True)[0:3]
    context = {'posts':posts, 'form': form}
    return render(request, 'portfolio/index.html', context)


@login_required(login_url='login')
def posts(request):
    posts = Post.objects.filter(active=True)
    myFilter = PostFilter(request.GET, queryset=posts)
    posts = myFilter.qs

    page = request.GET.get('page')
    paginator = Paginator(posts , 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts':posts, 'myFilter':myFilter}
    return render(request, 'portfolio/posts.html', context)


@login_required(login_url='login')
def post(request,slug):
    post = Post.objects.get(slug=slug)

    context = {'post': post}
    return render(request, 'portfolio/post.html', context)



#CRUD views
@login_required(login_url="login")
def createPost(request):
    form = PostForm()

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect("posts")

    context = {'form':form}
    return render(request, 'portfolio/post_form.html', context)
    

@login_required(login_url="login")
def updatePost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect("posts")

    context = {'form':form}
    return render(request, 'portfolio/post_form.html', context)


@login_required(login_url="login")
def deletePost(request, slug):
    post = Post.objects.get(slug=slug)

    if request.method == "POST":
        post.delete()
        return redirect('posts')

    context={'item':post}
    return render(request, "portfolio/delete.html", context)


@login_required(login_url='login')
def sendEmail(request):

    if request.method == 'POST':

        template = render_to_string('portfolio/email_template.html', {
            'name':request.POST['name'],
            'email':request.POST['email'],
            'message':request.POST['message'],
            })

        email = EmailMessage(
            request.POST['subject'],
            template,
            settings.EMAIL_HOST_USER,
            ['djngpython@gmail.com']
            )

        email.fail_silently=False
        email.send()

    return render(request, 'portfolio/email_sent.html')
    #return HttpResponse('Email was Sent!')

eWallet/portfolio/templates/portfolio/delete.html
{% extends 'wallet/main.html' %}
{% load static %}

{% block title %}
<title>Delete post</title>
{% endblock title %}

{% block content %}

<style type="text/css">
    body{
        background-color: #15202B;

    }

</style>

<div >
    <form action="" method="POST">
        {% csrf_token %}

        <p style="color: #fff">Are you sure you want to delete {{item}}?</p>
        <input class="btn btn-outline-danger" type="submit" value="confirm">
    </form>
</div>

{% endblock content%}

eWallet/portfolio/templates/portfolio/email_sent.html
{% extends 'wallet/main.html' %}
{% load static %}

{% block title %}
<title>Email Sent</title>
{% endblock title%}

{% block content %}

<style type="text/css">
	html, body{
		height: 100%;
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #15202B;

	}

	#success-box{
		max-width: 800px;
		height: auto;
		background-color: #606B56;
		border:1px solid #888;
		border-radius: 5px;
		padding: 15px;
	}

	#success-box p{
		font-size: 18px;
        color: #fff;
	}


</style>


<div id="page-wrapper">
    <div id="success-box" class="content-block">
        <h1>Thanks for reaching out!</h1>
       <p >Your message was successfully sent. I will do my best to get back to you in a timely manner :)</p>
        <a id="back-btn" class="btn btn-success" href="{% url 'home' %}">BACK TO HOME PAGE</a>
    </div>
</div>

{% endblock %}

eWallet/portfolio/templates/portfolio/email_template.html
{{name}}

{{email}}

{{message}}

eWallet/portfolio/templates/portfolio/index.html
{% extends 'wallet/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>Portfolio</title>
{% endblock title%}

{% block content %}


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-47692315-56"></script>
<script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());

	gtag('config', 'UA-47692315-56');
</script>

<style type="text/css">
	#profile_pic,#box{
		margin-top: 25px;
	}

</style>

<link id="theme-style" rel="stylesheet" type="text/css" href="">

<section class="s1">
	<div class="main-container">
		<div class="greeting-wrapper">
			<h1>Hi, I'm Haris Ahmad Khan</h1>
		</div>
		<div class="col-md">
			<h5 style="text-align: center;line-height: 0;">Personalize Theme</h5>
			<div id="theme-options-wrapper">
				<div data-mode="light" id="light-mode" class="theme-dot"></div>
				<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
				<div data-mode="green" id="green-mode" class="theme-dot"></div>
				<div data-mode="purple" id="purple-mode" class="theme-dot"></div>
			</div>
			<p id="settings-note">*Theme settings will be saved for<br>your next vist</p>
		</div>

		<div class="intro-wrapper">
			{% include 'portfolio/navbar_portfolio.html' %}
		</div>

		<div class="row">
			<div class="col-md-4">
				<img id="profile_pic" src="{{request.user.customer.profile_pic.url}}" alt="profile_pic">
			</div>
			<div class="col-md-4">
				<form action="" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{form|crispy}}
					<input class="btn btn-outline-info" type="submit" name="Update Information">
				</form>
			</div>
			<div class="col-md-4" id="box">
				<div id="preview-shadow">
					<div id="preview">
						<div id="corner-tl" class="corner"></div>
						<div id="corner-tr" class="corner"></div>
						<h3>What I Do</h3>
						<p>I'm an Electrical and Electronic engineer.I love Web App Development.</p>
						<div id="corner-br" class="corner"></div>
						<div id="corner-bl" class="corner"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="s2">
	<div class="main-container">
		<div class="about-wrapper">
			<div class="about-me">
				<h4>More about me</h4>
				<p>I love to make new things and develop our beloved country.</p>
				<p>While I'm busy doing a full time job still love to make new Websites.</p>
				<hr>
				<h4>TOP EXPERTISE</h4>
				<p>web developer with primary focus on Django: <a target="_blank" href="{% static 'resume.pdf' %}">Download Resume</a></p>

				<div id="skills">
					<ul>
						<li>Python</li>
						<li>Django</li>
						<li>JavaScript</li>
						<li>HTML & CSS</li>
						<li>Postgres</li>
					</ul>

					<ul>
						<li>Arduino</li>
						<li>Raspberry pi</li>
						<li>AWS (RDS/S3)</li>
						<li>Heroku</li>
						<li>FPGA</li>
					</ul>

				</div>

			</div>


			<div class="social-links">
				<img id="social_img" src="{% static 'images/billing.png' %}" alt="social_img">
				<h3>Find me on Instagram & GitHub</h3>

				<a target="_blank" href="https://www.instagram.com/haris18896">Instagram: @haris18896</a>
				<br>
				<a target="_blank" href="https://github.com/HarisAhmad43">GitHub: @HarisAhmad43</a>
			</div>
		</div>

	</div>
</section>

<section class="s1">
	<div class="main-container">
		<h3 style="text-align: center; ">Posts</h3>

		<div class="post-wrapper">
			{% for post in posts %}
			<div>
				<div class="post">
					<img class="thumbnail" src="{{post.thumbnail.url}}" alt="dash">
					<div class="post-preview">
						<h6 class="post-title">{{post.headline}}</h6>
						<p class="post-intro">{{post.sub_headline}}</p>
						<a href="{% url 'post' post.slug %}">Read More</a>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		<p align="center">
			<a href="{% url 'posts' %}">View more</a>
		</p>
	</div>
</section>

<section class="s2">
	<div class="main-container">
		<a href=""></a>
		<h3 style="text-align: center;">Get In Touch</h3>

		<form id="contact-form" method="POST" action="{% url 'send_email' %}">
			{% csrf_token %}
			<a name="contact"></a>

			<label>Name</label>
			<input class="input-field" type="text" name="name">

			<label>Subject</label>
			<input class="input-field" type="text" name="subject">

			<label>Email</label>
			<input class="input-field" type="text" name="email">

			<label>Message</label>
			<textarea class="input-field" name="message"></textarea>

			<input id="submit-btn" type="submit" value="Send">
		</form>
	</div>
</section>

<script type="text/javascript">
	let static = "{% static 'css' %}"
</script>

<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
{% endblock content%}

eWallet/portfolio/templates/portfolio/main_portfolio.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>PortFolio</title>

	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-47692315-56');
	</script>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
</head>
<body>

	{% include 'portfolio/navbar.html' %}

	{% block content %}
	<!-- Content goes here -->
	{% endblock content %}

</body>
</html>

eWallet/portfolio/templates/portfolio/navbar_portfolio.html
<div class="nav-wrapper">

	<!-- Link around dots-wrapper -->
	<a href="{% url 'user_home' %}">
		<div class="dots-wrapper">
			<div id="dot-1" class="browser-dot"></div>
			<div id="dot-2" class="browser-dot"></div>
			<div id="dot-3" class="browser-dot"></div>
		</div>
	</a>


	<ul id="navigation">
		<li><a class="btn btn-outline-info" href="{% url 'user_home' %}#contact">Contact</a></li>

		{% if request.user.is_authenticated %}
			<li><a class="btn btn-outline-info" href="{% url 'create_post' %}" >Create Post</a> </li>
		{% endif %}

	</ul>
</div>

eWallet/portfolio/templates/portfolio/post.html
{% extends 'wallet/main.html' %}
{% load static %}

{% block title %}
<title>{{post.headline}}</title>
{% endblock title%}

{% block content %}

<style>
    img{
        width: 100%;
        object-fit: cover;
        height: 90vh;

    }
   body{
        background-color: #15202B;

    }

    h1{
        color: #4cb4c7;
    }
    .main-container{
        color: #FFFFFF;
    }

</style>

<div class="main-container">
    <img src="{{post.thumbnail.url}}" alt="thumbnail">
    <h1>{{post.headline}}</h1>
    <h4>{{post.sub_headline|linebreaks}}</h4>
    <p >{{post.body|safe}}</p>
</div>




{% endblock content %}

eWallet/portfolio/templates/portfolio/post_form.html
{% extends 'wallet/main.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>Post Form</title>
{% endblock title%}

{% block content %}
<style type="text/css">
    body{
        color: #fff;
        background-color: #15202B;
    }
    #div_id_tags > div{
        max-height: 100px;
        overflow-y: scroll;
        border: 1px solid #888;
        padding: 5px;
        border-radius: 5px;
    }
    h3{
        color: #4cb4c7;
    }
    .main-container{
        color: #FFFFFF;
    }
</style>

<div class="main-container">
    <h3>Post Form</h3>

    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <input class="btn btn-outline-primary" type="submit" value="submit Post">

    </form>
</div>

{% endblock content%}

eWallet/portfolio/templates/portfolio/posts.html
{% extends 'wallet/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
<title>Posts</title>
{% endblock title%}

{% block content %}

<style type="text/css">
	.tag{
		display:inline-block;
		color:#fff;
		background-color: #888;
		border-radius: 5px;
		margin: 2px;
		padding: 2px 5px;
		font-size: 12px;
	}

	#id_tags{
		overflow-y: scroll;
		max-height: 100px;
		border: 1px solid #888;
		padding: 5px;
		border-radius: 5px;
	}

	body{
		background-color: #15202B;

	}
</style>


<h1 style="color: #0f74a8">Posts</h1>

<form id="seachForm" method="GET">
	{{myFilter.form|crispy}}
	<input type="submit" class="btn btn-outline-info" value="Search">
</form>

<div class="container">
	<div class="post-wrapper">
		{% for post in posts %}
		<div>
			<div class="post">
				<img class="thumbnail" src="{{post.thumbnail.url}}" alt="dash">
				<div class="post-preview">
					<h6 class="post-title" >{{post.headline}}</h6>
					<p class="post-intro">{{post.sub_headline}}</p>
					<a class="btn btn-outline-info" href="{% url 'post' post.slug %}"> Read More</a>

					{% if request.user.is_authenticated %}
					<a class="btn btn-outline-info" href="{% url 'update_post' post.slug %}">Edit</a>
					<a class="btn btn-outline-danger" href="{% url 'delete_post' post.slug %}">Delete</a>
					{% endif %}

					<hr>
					{% for tag in post.tags.all %}
					<span class="tag">{{tag}}</span>
					{% endfor %}
					<hr>

				</div>
			</div>
		</div>

		{% empty %}
		<h3>No posts found...</h3>

		{% endfor %}

	</div>

	<div class="row">
		{% if posts.has_other_pages %}

		<ul class="pagination">
			{% if posts.has_previous %}
			<li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>

			<li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
			{% endif %}

			{% for i in posts.paginator.page_range %}
			{% if posts.number == i %}
			<li class="page-item"><a  class="active page-link">{{i}}</a></li>
			{% else %}
			<li class="page-item"><a data-page="{{i}}"  href="?page={{i}}" class="page-link">{{i}}</a></li>
			{% endif %}
			{% endfor %}

			{% if posts.has_next %}
			<li class="page-item"><a data-page="{{posts.paginator_page_number}}" href="?page={{posts.paginator_page_number}}" class="page-link">Last</a></li>
			<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
			{% endif %}
		</ul>

		{% endif %}
	</div>
</div>
<a class="btn btn-outline-info" href="{% url 'create_post' %}" >Create Post</a>

<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	for(var i=0; pageLinks.length; i++){
		pageLinks[i].addEventListener('click', function (e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('page', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden>`
			searchForm.submit()
		})
	}
</script>
{% endblock content%}